server {
    listen 80;
    server_name sellhelper.gtaitson.space;
    
    root /var/www/sellhelper.gtaitson.space;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location ~* \.(html|css|js|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1d;
        add_header Cache-Control "public, immutable";
    }
}
